name: test_workflow
on:
  push:
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v3

      - name: install node
        run: actions/setup-node@v4

      - name: install npm
        run: npm install

      - name: test
        run: npm test  
